name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Image Build
    runs-on: ubuntu-22.04
    continue-on-error: false

    strategy:
      max-parallel: 8
      matrix:
        device:
          - raphael

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential uuid-dev clang llvm iasl nasm \
            gcc-aarch64-linux-gnu abootimg \
            python3-distutils python3-pil python3-git gettext

      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh --all -c DEV

      - name: List files
        run: ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: img
          path: "*.img"
